name=EDP-Platform-ESP-IDF
version=0.1.0
author=Simon J. Stuart
maintainer=Simon J. Stuart
sentence=ESP-IDF backend implementations for EDP-Platform.
paragraph=Concrete ESP-IDF environment implementations of ESPressio Platform capabilities, beginning with the lock-free AtomicWord32 concurrency provider.
category=Other
url=https://espressio.org
architectures=esp32
includes=ESPressio_Platform_ESP_IDF.hpp
depends=EDP-Platform (>=0.1.0 && <0.2.0)
