name=EDP-Platform-ESP-IDF
version=0.1.0
author=Simon J. Stuart
maintainer=Simon J. Stuart
sentence=ESP-IDF providers for ESPressio Platform abstractions.
paragraph=ESP-IDF-specific static execution-context and spin-lock implementations selected through ESPressio Composition.
category=Other
url=https://espressio.org
architectures=*
includes=ESPressio_Platform_ESP_IDF.hpp
depends=EDP-Platform (>=0.1.0 && <0.2.0)
